DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user` (
`id`  BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`username`  VARCHAR(36)  NOT NULL COMMENT '用户名',
`password`  VARCHAR(36)  NOT NULL COMMENT '密码',
`state` TINYINT NULL DEFAULT '0' COMMENT '用户状态(0=正常,1=禁用)',
`create_time` DATETIME NULL DEFAULT NOW() COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
PRIMARY KEY (`id`),
INDEX `idx_username` (`username`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';